---
title: "NYC Tree Dashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
    social: menu
    source_code: https://github.com/anishababu62442/Tree-Dashboard
    theme: spacelab
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
library(flexdashboard)
library(rio)
library(tidyverse)
library(tigris)
library(dplyr)
library(leaflet)
library(sp)
library(ggmap) # need to cite!!
library(maptools)
library(broom)
library(httr)
library(rgdal)
library(gganimate)
library(gifski)
library(png)
library(nycgeo)
library(sf)

# IF YOU DO NOT HAVE TREE DATA YET
tree_census <- read_csv("https://data.cityofnewyork.us/api/views/uvpi-gqnh/rows.csv")

# IF YOU ALREADY DOWNLOADED TREE DATA
# tree_census <- import("2015_Street_Tree_Census_-_Tree_Data.csv")

# Download NYC neighborhood data 
r <- GET('http://data.beta.nyc//dataset/0ff93d2d-90ba-457c-9f7e-39e47bf2ac5f/resource/35dd04fb-81b3-479b-a074-a27a37888ce7/download/d085e2f8d0b54d4590b1e7d1f35594c1pediacitiesnycneighborhoods.geojson')
nyc_neighborhoods <- readOGR(content(r,'text'), 'OGRGeoJSON', verbose = F)
nyc_neighborhoods_df <- tidy(nyc_neighborhoods)

```

Visualization 1
======================================================================

What is this? {.sidebar}
----------------------------------------------------------------------

How many trees are there in each of the NYC neighborhoods? Trees and other plants can improve the environment and beauty of an area. This heat map of NYC serves to show which areas have more trees - and may therefore be preferable to live in.

Version 1: Due to difficulties with the dataset (i.e. neighborhood names did not match up perfectly), some neighborhoods were left without any data, making this a very sparse visualization.

Version 2: The second version used census tract regions. Due to standardization of census tract codes, all tracts in the dataset matched up (and only a handful did not have data). Additional styling changes improve the readability as well. 

Column {.tabset}
-----------------------------------------------------------------------

### Version 1

```{r vis 1 ver 1}
# Count neighborhood trees
trees_by_neighborhood <- tree_census %>%
  group_by(neighborhood = nta_name) %>%
  summarize(num_trees=n())

# Join data
tree_neighborhood <- tidy(nyc_neighborhoods, region="neighborhood") %>%
  left_join(., trees_by_neighborhood, by=c("id"="neighborhood")) 

# Tree density heat map
ggplot() + 
  geom_polygon(data=tree_neighborhood, 
               aes(x=long, y=lat, group=group, fill=num_trees),
               color="black") +
  theme_void() +
  labs(title = "Tree Density in NYC",
       fill = "Number of Trees") 

```

### Version 2

```{r vis 1 ver 2}
# Count neighborhood trees
trees_by_tract <- tree_census %>%
  group_by(tract = boro_ct) %>%
  summarize(num_trees=n()) %>%
  mutate(tract = as.character(tract))

# join tree & tract data
nyc_tracts <- nyc_boundaries(geography = "tract")
tree_tract <- left_join(nyc_tracts, trees_by_tract, by=c("borough_tract_id"="tract"))

# plot map
tree_tract %>%
  ggplot() +
  geom_sf(aes(fill=num_trees), lwd=0) +
  theme_minimal() +
  geom_text(x=960000, y=130000, label="Staten\nIsland", color="gray50") +
  geom_text(x=1045000, y=270000, label="Bronx", color="gray50") +
  geom_text(x=974800, y=230000, label="Manhattan", color="gray50") +
  geom_text(x=987000, y=143000, label="Brooklyn", color="gray50") +
  geom_text(x=1059000, y=230000, label="Queens", color="gray50") +
  labs(fill = "Number of Trees",
       title = "Distribution of Trees in NYC",
       caption = "Gray regions represent census tracts without data") +
  theme(legend.position = c(0.2, 0.8), plot.title = element_text(hjust=0.2)) +
  scale_fill_distiller(palette="Greens")

```

Visualization 2
======================================================================

What is this? {.sidebar}
----------------------------------------------------------------------

What kinds of problems harm the health of trees in NYC? Here, the average diameter of NYC trees is plotted based on the type of problem observed (i.e. decorations, wiring, etc.). This aims to educate city planners and/or environmentalists on what kinds of tree additions may be most detrimental to tree health. (Tree diameter is used a proxy for tree health)

Version 1: Unnecessary color and unsorted bars make it difficult to interpret this bar chart. 

Version 2: The second version sorts problem type by problem location (branch/root/trunk), and sorts bars by average diameter to improve readability. Additional formatting also improves clarity.

Column {.tabset}
-----------------------------------------------------------------------

### Version 1

```{r vis 2 ver 1}
# change values to 0/1 numeric
tree_census[tree_census == "No"] <- "0"  
tree_census[tree_census == "Yes"] <- "1"
tree_census$root_stone <- as.numeric(tree_census$root_stone)
tree_census$root_grate <- as.numeric(tree_census$root_grate)
tree_census$root_other <-as.numeric(tree_census$root_other)
tree_census$trunk_wire <- as.numeric(tree_census$trunk_wire)
tree_census$trnk_light <- as.numeric(tree_census$trnk_light)
tree_census$trnk_other <- as.numeric(tree_census$trnk_other)
tree_census$brch_shoe <- as.numeric(tree_census$brch_shoe)
tree_census$brch_light <- as.numeric(tree_census$brch_light)
tree_census$brch_other <- as.numeric(tree_census$brch_other)

tree_damage <- tree_census %>%
  filter(problems != "None") %>%
  pivot_longer(cols = root_stone:brch_other, 
               names_to = "problem_type", 
               values_to = "count") %>%
  group_by(problem_type) %>%
  filter(count == 1) %>%
  summarize(average_dbh = mean(tree_dbh))
tree_damage$problem_type <- as.factor(tree_damage$problem_type) 
tree_damage$problem_type <- recode(tree_damage$problem_type, 
                                   brch_light="Lights in Branches",
                                   brch_shoe = "Shoes in Branches",
                                   brch_other = "Other Branch Problem",
                                   trunk_wire = "Wire on Trunk",
                                   trnk_light = "Lights on Trunk",
                                   trnk_other = "Other Trunk Problems",
                                   root_stone = "Paving Stones on Root",
                                   root_grate = "Grate on Root",
                                   root_other = "Other Root Problems")

tree_damage %>%
  ggplot(aes(x = problem_type, y = average_dbh)) +
  geom_bar(stat = "identity", aes(fill = problem_type)) +
  labs(title = "Tree Diameter by Problem Type",
       x = "Problem Type",
       y = "Average Tree Diameter") +
  theme(legend.position = "none") +
  theme(axis.text.x = element_text(angle = 60, hjust=1))

```

### Version 2

```{r vis 2 ver 2}
# change values to 0/1 numeric
tree_census[tree_census=="No"] <- 0
tree_census[tree_census=="Yes"] <- 1

tree_damage <- tree_census %>%
  filter(problems != "None") %>%
  pivot_longer(cols = root_stone:brch_other, 
               names_to = "problem_type", 
               values_to = "count") %>%
  group_by(problem_type) %>%
  filter(count == 1) %>%
  summarize(average_dbh = mean(tree_dbh)) %>%
  mutate(problem_type = fct_reorder(problem_type, average_dbh))

tree_damage <- tree_damage %>%
  mutate(type_color = case_when(
    startsWith(as.character(problem_type), "br") ~ "Branch",
    startsWith(as.character(problem_type), "tr") ~ "Trunk",
    startsWith(as.character(problem_type), "ro") ~ "Root"))

tree_damage$problem_type <- as.factor(tree_damage$problem_type) 
tree_damage$problem_type <- recode(tree_damage$problem_type, 
                                   brch_light="Hanging Lights/Wires",
                                   brch_shoe = "Hanging Shoes",
                                   brch_other = "Misc Branch",
                                   trunk_wire = "Wrapped Wire/Rope",
                                   trnk_light = "Installed Lights",
                                   trnk_other = "Misc Trunk",
                                   root_stone = "Paving Stones",
                                   root_grate = "Metal Grate",
                                   root_other = "Misc Root")

tree_damage %>%
  ggplot(aes(x = problem_type, y = average_dbh)) +
  geom_bar(stat = "identity", aes(fill = type_color), color = "gray50") +
  labs(title = "Tree Diameter by Problem Type",
       x = "Problem Type",
       y = "Average Tree Diameter (in)",
       fill = "Tree Area") +
  coord_flip() +
  scale_fill_brewer(palette="Greens") + 
  theme(legend.justification=c(1,0), 
        legend.position=c(1, 0),
        legend.background = element_blank()) +
  theme(panel.background = element_rect(fill = "white"),
        panel.grid.major = element_line(color = "gray90"))

```

Visualization 3
======================================================================

What is this? {.sidebar}
----------------------------------------------------------------------

Where can you find the most diverse distribution of trees in NYC? This visualization plots the number of tree species across different neighborhoods. Like the first visualization, this serves to demonstrate which areas of NYC may have the best environment and beauty.

Version 1: Animation was used to cycle through each neighborhood. However, since only one neighborhood appears at a time, it is difficult to make comparisons

Version 2: The second version displays all neighborhoods at once. However, with more than 100 different neighborhoods, the labels are jumbled and difficult to read.

Version 3: The third version displays just the top ten and bottom ten neighborhoods for the number of tree species.

Column {.tabset}
-----------------------------------------------------------------------

### Version 1

```{r vis 3 ver 1}
# count species types
tree_species <- tree_census %>%
  group_by(nta_name) %>%
  summarize(num_trees=n(), num_species = length(unique(spc_common))) %>%
  pivot_longer(cols = num_trees:num_species, 
               names_to = "type_count",
               values_to = "count")

species_plot <- tree_species %>%
  filter(type_count == "num_species") %>%
  ggplot(aes(x = count, y = type_count)) +
  geom_bar(stat = "identity", fill = "skyblue3", color = "gray70") +
  labs(x = "Tree Species Count") +
  theme(axis.text.y=element_blank(),
        axis.title.y=element_blank())
species_plot <- species_plot +
  transition_states(nta_name,
                    transition_length = 2,
                    state_length = 1) +
  labs(title = 'Number of Tree Species in: {closest_state}')

animate(species_plot,fps = 1)

```

### Version 2

```{r vis 3 ver 2}
# count species types
tree_species <- tree_census %>%  
  group_by(nta_name, borough) %>%
  summarize(num_species = length(unique(spc_common))) 
tree_species$nta_name <- reorder(tree_species$nta_name, tree_species$num_species)

tree_species %>%
  ggplot(aes(x = num_species, y = nta_name)) +
  geom_bar(stat = "identity", fill = "#9dad7f", color = "#9dad7f") +
  labs(x = "Tree Species Count") +
  theme(axis.title.y=element_blank()) +
  theme(axis.text.x = element_text(color = "black")) +
  labs(title = 'Number of Tree Species in NYC Neighborhoods')


```

### Version 3

```{r vis 3 ver 3}
# count species types
tree_species <- tree_census %>%  
  group_by(nta_name, borough) %>%
  summarize(num_species = length(unique(spc_common))) 
tree_species <- tree_species[order(tree_species$num_species),]

tree_species <- rbind(head(tree_species,10), tail(tree_species,10))

tree_species$nta_name[2] <- "East New York (Queens)"
tree_species$nta_name[17] <- "East New York (Brooklyn)"
tree_species$nta_name <- reorder(tree_species$nta_name, tree_species$num_species)

highlight_species <- tree_species %>%
  filter(num_species > 40)
  
tree_species %>%
  ggplot(aes(x = num_species, y = nta_name)) +
  geom_bar(stat = "identity", fill = "#9dad7f") +
  geom_bar(stat = "identity", 
           data = highlight_species,
           aes(x=num_species,y=nta_name), 
           fill='#0B6623') +
  labs(x = "Tree Species Count") +
  theme(axis.title.y=element_blank()) +
  theme(axis.text.x = element_text(color = "black")) +
  labs(title = 'Top/bottom NYC neighborhoods for tree diversity') +
  theme(panel.background = element_rect(fill = "white"),
        panel.grid.major = element_line(color = "gray90")) +
  theme(plot.title = element_text(hjust = 2))

```
